[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
time-locked-wallet = "G9C4ivjLy46CfRH8wbxBLDX4eSunQaZopoiSK2E9LymC"

[programs.devnet]
time-locked-wallet = "G9C4ivjLy46CfRH8wbxBLDX4eSunQaZopoiSK2E9LymC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
